<?php
// From https://github.com/Kdyby/DoctrineMoney/blob/master/data/currencies.sql
return array(
	'AED' => array('name' => 'UAE Dirham', 'number' => '784', 'subunits' => 100),
	'AFN' => array('name' => 'Afghani', 'number' => '971', 'subunits' => 100),
	'ALL' => array('name' => 'Lek', 'number' => '008', 'subunits' => 100),
	'AMD' => array('name' => 'Armenian Dram', 'number' => '051', 'subunits' => 100),
	'ANG' => array('name' => 'Netherlands Antillean Guilder', 'number' => '532', 'subunits' => 100),
	'AOA' => array('name' => 'Kwanza', 'number' => '973', 'subunits' => 100),
	'ARS' => array('name' => 'Argentine Peso', 'number' => '032', 'subunits' => 100),
	'AUD' => array('name' => 'Australian Dollar', 'number' => '036', 'subunits' => 100),
	'AWG' => array('name' => 'Aruban Florin', 'number' => '533', 'subunits' => 100),
	'AZN' => array('name' => 'Azerbaijanian Manat', 'number' => '944', 'subunits' => 100),
	'BAM' => array('name' => 'Convertible Mark', 'number' => '977', 'subunits' => 100),
	'BBD' => array('name' => 'Barbados Dollar', 'number' => '052', 'subunits' => 100),
	'BDT' => array('name' => 'Taka', 'number' => '050', 'subunits' => 100),
	'BGN' => array('name' => 'Bulgarian Lev', 'number' => '975', 'subunits' => 100),
	'BHD' => array('name' => 'Bahraini Dinar', 'number' => '048', 'subunits' => 1000),
	'BIF' => array('name' => 'Burundi Franc', 'number' => '108', 'subunits' => 1),
	'BMD' => array('name' => 'Bermudian Dollar', 'number' => '060', 'subunits' => 100),
	'BND' => array('name' => 'Brunei Dollar', 'number' => '096', 'subunits' => 100),
	'BOB' => array('name' => 'Boliviano', 'number' => '068', 'subunits' => 100),
	'BOV' => array('name' => 'Mvdol', 'number' => '984', 'subunits' => 100),
	'BRL' => array('name' => 'Brazilian Real', 'number' => '986', 'subunits' => 100),
	'BSD' => array('name' => 'Bahamian Dollar', 'number' => '044', 'subunits' => 100),
	'BTN' => array('name' => 'Ngultrum', 'number' => '064', 'subunits' => 100),
	'BWP' => array('name' => 'Pula', 'number' => '072', 'subunits' => 100),
	'BYR' => array('name' => 'Belarussian Ruble', 'number' => '974', 'subunits' => 1),
	'BZD' => array('name' => 'Belize Dollar', 'number' => '084', 'subunits' => 100),
	'CAD' => array('name' => 'Canadian Dollar', 'number' => '124', 'subunits' => 100),
	'CDF' => array('name' => 'Congolese Franc', 'number' => '976', 'subunits' => 100),
	'CHE' => array('name' => 'WIR Euro', 'number' => '947', 'subunits' => 100),
	'CHF' => array('name' => 'Swiss Franc', 'number' => '756', 'subunits' => 100),
	'CHW' => array('name' => 'WIR Franc', 'number' => '948', 'subunits' => 100),
	'CLF' => array('name' => 'Unidad de Fomento', 'number' => '990', 'subunits' => 10000),
	'CLP' => array('name' => 'Chilean Peso', 'number' => '152', 'subunits' => 1),
	'CNY' => array('name' => 'Yuan Renminbi', 'number' => '156', 'subunits' => 100),
	'COP' => array('name' => 'Colombian Peso', 'number' => '170', 'subunits' => 100),
	'COU' => array('name' => 'Unidad de Valor Real', 'number' => '970', 'subunits' => 100),
	'CRC' => array('name' => 'Costa Rican Colon', 'number' => '188', 'subunits' => 100),
	'CUC' => array('name' => 'Peso Convertible', 'number' => '931', 'subunits' => 100),
	'CUP' => array('name' => 'Cuban Peso', 'number' => '192', 'subunits' => 100),
	'CVE' => array('name' => 'Cape Verde Escudo', 'number' => '132', 'subunits' => 100),
	'CZK' => array('name' => 'Czech Koruna', 'number' => '203', 'subunits' => 100),
	'DJF' => array('name' => 'Djibouti Franc', 'number' => '262', 'subunits' => 1),
	'DKK' => array('name' => 'Danish Krone', 'number' => '208', 'subunits' => 100),
	'DOP' => array('name' => 'Dominican Peso', 'number' => '214', 'subunits' => 100),
	'DZD' => array('name' => 'Algerian Dinar', 'number' => '012', 'subunits' => 100),
	'EGP' => array('name' => 'Egyptian Pound', 'number' => '818', 'subunits' => 100),
	'ERN' => array('name' => 'Nakfa', 'number' => '232', 'subunits' => 100),
	'ETB' => array('name' => 'Ethiopian Birr', 'number' => '230', 'subunits' => 100),
	'EUR' => array('name' => 'Euro', 'number' => '978', 'subunits' => 100),
	'FJD' => array('name' => 'Fiji Dollar', 'number' => '242', 'subunits' => 100),
	'FKP' => array('name' => 'Falkland Islands Pound', 'number' => '238', 'subunits' => 100),
	'GBP' => array('name' => 'Pound Sterling', 'number' => '826', 'subunits' => 100),
	'GEL' => array('name' => 'Lari', 'number' => '981', 'subunits' => 100),
	'GHS' => array('name' => 'Ghana Cedi', 'number' => '936', 'subunits' => 100),
	'GIP' => array('name' => 'Gibraltar Pound', 'number' => '292', 'subunits' => 100),
	'GMD' => array('name' => 'Dalasi', 'number' => '270', 'subunits' => 100),
	'GNF' => array('name' => 'Guinea Franc', 'number' => '324', 'subunits' => 1),
	'GTQ' => array('name' => 'Quetzal', 'number' => '320', 'subunits' => 100),
	'GYD' => array('name' => 'Guyana Dollar', 'number' => '328', 'subunits' => 100),
	'HKD' => array('name' => 'Hong Kong Dollar', 'number' => '344', 'subunits' => 100),
	'HNL' => array('name' => 'Lempira', 'number' => '340', 'subunits' => 100),
	'HRK' => array('name' => 'Croatian Kuna', 'number' => '191', 'subunits' => 100),
	'HTG' => array('name' => 'Gourde', 'number' => '332', 'subunits' => 100),
	'HUF' => array('name' => 'Forint', 'number' => '348', 'subunits' => 100),
	'IDR' => array('name' => 'Rupiah', 'number' => '360', 'subunits' => 100),
	'ILS' => array('name' => 'New Israeli Sheqel', 'number' => '376', 'subunits' => 100),
	'INR' => array('name' => 'Indian Rupee', 'number' => '356', 'subunits' => 100),
	'IQD' => array('name' => 'Iraqi Dinar', 'number' => '368', 'subunits' => 1000),
	'IRR' => array('name' => 'Iranian Rial', 'number' => '364', 'subunits' => 100),
	'ISK' => array('name' => 'Iceland Krona', 'number' => '352', 'subunits' => 1),
	'JMD' => array('name' => 'Jamaican Dollar', 'number' => '388', 'subunits' => 100),
	'JOD' => array('name' => 'Jordanian Dinar', 'number' => '400', 'subunits' => 1000),
	'JPY' => array('name' => 'Yen', 'number' => '392', 'subunits' => 1),
	'KES' => array('name' => 'Kenyan Shilling', 'number' => '404', 'subunits' => 100),
	'KGS' => array('name' => 'Som', 'number' => '417', 'subunits' => 100),
	'KHR' => array('name' => 'Riel', 'number' => '116', 'subunits' => 100),
	'KMF' => array('name' => 'Comoro Franc', 'number' => '174', 'subunits' => 1),
	'KPW' => array('name' => 'North Korean Won', 'number' => '408', 'subunits' => 100),
	'KRW' => array('name' => 'Won', 'number' => '410', 'subunits' => 1),
	'KWD' => array('name' => 'Kuwaiti Dinar', 'number' => '414', 'subunits' => 1000),
	'KYD' => array('name' => 'Cayman Islands Dollar', 'number' => '136', 'subunits' => 100),
	'KZT' => array('name' => 'Tenge', 'number' => '398', 'subunits' => 100),
	'LAK' => array('name' => 'Kip', 'number' => '418', 'subunits' => 100),
	'LBP' => array('name' => 'Lebanese Pound', 'number' => '422', 'subunits' => 100),
	'LKR' => array('name' => 'Sri Lanka Rupee', 'number' => '144', 'subunits' => 100),
	'LRD' => array('name' => 'Liberian Dollar', 'number' => '430', 'subunits' => 100),
	'LSL' => array('name' => 'Loti', 'number' => '426', 'subunits' => 100),
	'LTL' => array('name' => 'Lithuanian Litas', 'number' => '440', 'subunits' => 100),
	'LYD' => array('name' => 'Libyan Dinar', 'number' => '434', 'subunits' => 1000),
	'MAD' => array('name' => 'Moroccan Dirham', 'number' => '504', 'subunits' => 100),
	'MDL' => array('name' => 'Moldovan Leu', 'number' => '498', 'subunits' => 100),
	'MGA' => array('name' => 'Malagasy Ariary', 'number' => '969', 'subunits' => 100),
	'MKD' => array('name' => 'Denar', 'number' => '807', 'subunits' => 100),
	'MMK' => array('name' => 'Kyat', 'number' => '104', 'subunits' => 100),
	'MNT' => array('name' => 'Tugrik', 'number' => '496', 'subunits' => 100),
	'MOP' => array('name' => 'Pataca', 'number' => '446', 'subunits' => 100),
	'MRO' => array('name' => 'Ouguiya', 'number' => '478', 'subunits' => 100),
	'MUR' => array('name' => 'Mauritius Rupee', 'number' => '480', 'subunits' => 100),
	'MVR' => array('name' => 'Rufiyaa', 'number' => '462', 'subunits' => 100),
	'MWK' => array('name' => 'Kwacha', 'number' => '454', 'subunits' => 100),
	'MXN' => array('name' => 'Mexican Peso', 'number' => '484', 'subunits' => 100),
	'MXV' => array('name' => 'Mexican Unidad de Inversion (UDI)', 'number' => '979', 'subunits' => 100),
	'MYR' => array('name' => 'Malaysian Ringgit', 'number' => '458', 'subunits' => 100),
	'MZN' => array('name' => 'Mozambique Metical', 'number' => '943', 'subunits' => 100),
	'NAD' => array('name' => 'Namibia Dollar', 'number' => '516', 'subunits' => 100),
	'NGN' => array('name' => 'Naira', 'number' => '566', 'subunits' => 100),
	'NIO' => array('name' => 'Cordoba Oro', 'number' => '558', 'subunits' => 100),
	'NOK' => array('name' => 'Norwegian Krone', 'number' => '578', 'subunits' => 100),
	'NPR' => array('name' => 'Nepalese Rupee', 'number' => '524', 'subunits' => 100),
	'NZD' => array('name' => 'New Zealand Dollar', 'number' => '554', 'subunits' => 100),
	'OMR' => array('name' => 'Rial Omani', 'number' => '512', 'subunits' => 1000),
	'PAB' => array('name' => 'Balboa', 'number' => '590', 'subunits' => 100),
	'PEN' => array('name' => 'Nuevo Sol', 'number' => '604', 'subunits' => 100),
	'PGK' => array('name' => 'Kina', 'number' => '598', 'subunits' => 100),
	'PHP' => array('name' => 'Philippine Peso', 'number' => '608', 'subunits' => 100),
	'PKR' => array('name' => 'Pakistan Rupee', 'number' => '586', 'subunits' => 100),
	'PLN' => array('name' => 'Zloty', 'number' => '985', 'subunits' => 100),
	'PYG' => array('name' => 'Guarani', 'number' => '600', 'subunits' => 1),
	'QAR' => array('name' => 'Qatari Rial', 'number' => '634', 'subunits' => 100),
	'RON' => array('name' => 'New Romanian Leu', 'number' => '946', 'subunits' => 100),
	'RSD' => array('name' => 'Serbian Dinar', 'number' => '941', 'subunits' => 100),
	'RUB' => array('name' => 'Russian Ruble', 'number' => '643', 'subunits' => 100),
	'RWF' => array('name' => 'Rwanda Franc', 'number' => '646', 'subunits' => 1),
	'SAR' => array('name' => 'Saudi Riyal', 'number' => '682', 'subunits' => 100),
	'SBD' => array('name' => 'Solomon Islands Dollar', 'number' => '090', 'subunits' => 100),
	'SCR' => array('name' => 'Seychelles Rupee', 'number' => '690', 'subunits' => 100),
	'SDG' => array('name' => 'Sudanese Pound', 'number' => '938', 'subunits' => 100),
	'SEK' => array('name' => 'Swedish Krona', 'number' => '752', 'subunits' => 100),
	'SGD' => array('name' => 'Singapore Dollar', 'number' => '702', 'subunits' => 100),
	'SHP' => array('name' => 'Saint Helena Pound', 'number' => '654', 'subunits' => 100),
	'SLL' => array('name' => 'Leone', 'number' => '694', 'subunits' => 100),
	'SOS' => array('name' => 'Somali Shilling', 'number' => '706', 'subunits' => 100),
	'SRD' => array('name' => 'Surinam Dollar', 'number' => '968', 'subunits' => 100),
	'SSP' => array('name' => 'South Sudanese Pound', 'number' => '728', 'subunits' => 100),
	'STD' => array('name' => 'Dobra', 'number' => '678', 'subunits' => 100),
	'SVC' => array('name' => 'El Salvador Colon', 'number' => '222', 'subunits' => 100),
	'SYP' => array('name' => 'Syrian Pound', 'number' => '760', 'subunits' => 100),
	'SZL' => array('name' => 'Lilangeni', 'number' => '748', 'subunits' => 100),
	'THB' => array('name' => 'Baht', 'number' => '764', 'subunits' => 100),
	'TJS' => array('name' => 'Somoni', 'number' => '972', 'subunits' => 100),
	'TMT' => array('name' => 'Turkmenistan New Manat', 'number' => '934', 'subunits' => 100),
	'TND' => array('name' => 'Tunisian Dinar', 'number' => '788', 'subunits' => 1000),
	'TOP' => array('name' => 'Pa’anga', 'number' => '776', 'subunits' => 100),
	'TRY' => array('name' => 'Turkish Lira', 'number' => '949', 'subunits' => 100),
	'TTD' => array('name' => 'Trinidad and Tobago Dollar', 'number' => '780', 'subunits' => 100),
	'TWD' => array('name' => 'New Taiwan Dollar', 'number' => '901', 'subunits' => 100),
	'TZS' => array('name' => 'Tanzanian Shilling', 'number' => '834', 'subunits' => 100),
	'UAH' => array('name' => 'Hryvnia', 'number' => '980', 'subunits' => 100),
	'UGX' => array('name' => 'Uganda Shilling', 'number' => '800', 'subunits' => 1),
	'USD' => array('name' => 'US Dollar', 'number' => '840', 'subunits' => 100),
	'USN' => array('name' => 'US Dollar (Next day)', 'number' => '997', 'subunits' => 100),
	'UYI' => array('name' => 'Uruguay Peso en Unidades Indexadas (URUIURUI)', 'number' => '940', 'subunits' => 1),
	'UYU' => array('name' => 'Peso Uruguayo', 'number' => '858', 'subunits' => 100),
	'UZS' => array('name' => 'Uzbekistan Sum', 'number' => '860', 'subunits' => 100),
	'VEF' => array('name' => 'Bolivar', 'number' => '937', 'subunits' => 100),
	'VND' => array('name' => 'Dong', 'number' => '704', 'subunits' => 1),
	'VUV' => array('name' => 'Vatu', 'number' => '548', 'subunits' => 1),
	'WST' => array('name' => 'Tala', 'number' => '882', 'subunits' => 100),
	'XAF' => array('name' => 'CFA Franc BEAC', 'number' => '950', 'subunits' => 1),
	'XCD' => array('name' => 'East Caribbean Dollar', 'number' => '951', 'subunits' => 100),
	'XDR' => array('name' => 'SDR (Special Drawing Right)', 'number' => '960', 'subunits' => 1),
	'XOF' => array('name' => 'CFA Franc BCEAO', 'number' => '952', 'subunits' => 1),
	'XPF' => array('name' => 'CFP Franc', 'number' => '953', 'subunits' => 1),
	'XSU' => array('name' => 'Sucre', 'number' => '994', 'subunits' => 1),
	'XUA' => array('name' => 'ADB Unit of Account', 'number' => '965', 'subunits' => 1),
	'YER' => array('name' => 'Yemeni Rial', 'number' => '886', 'subunits' => 100),
	'ZAR' => array('name' => 'Rand', 'number' => '710', 'subunits' => 100),
	'ZMW' => array('name' => 'Zambian Kwacha', 'number' => '967', 'subunits' => 100),
	'ZWL' => array('name' => 'Zimbabwe Dollar', 'number' => '932', 'subunits' => 100),
);
